### ISSUE TITLE
Grid View Issue in v1.51

### ISSUE THREAD

**Issue by umbertomarotta** [darklinkpower/Helium#46] opened 2023-11-06 14:10 UTC
### Bug Description

![image](https://github.com/darklinkpower/Helium/assets/3079597/640d058b-1e00-4baf-9fb5-e68f11e930ae)

Not sure if this is caused by any other add-on or some weird dpi settings, but when you hover the pointer over a cover, version v1.51 displays the issue shown in the image above.

Downgrading to 1.50 fixes it.

**Comment by sengtsan** [comment] 2023-12-07 22:59
![helium](https://github.com/darklinkpower/Helium/assets/63714826/5505f806-30b2-4094-a208-cf623a17551b)

Thanks for responding and apologies for the lack of clarity. 

https://github.com/darklinkpower/Helium/assets/63714826/6e2d778c-a054-40db-ba1e-f3197987f61a

In version 1.52, when I rest the mouse cursor over the top left cover in Playnite's desktop mode, instead of the "play/install" and "information" icons appearing within the cover, a space is created underneath the cover in which an enlarged version of those icons appear. I have attached a screenshot to illustrate. As you can see a space is created under every corresponding row of covers when the mouse rests on the top left cover.  In version 1.50, the icons appeared as an overlay within the cover. 

Additionally, as of version 1.51, those icons do not appear at all when I rest the mouse over any of the other covers. In 1.50 when the mouse was rested on any individual cover, an overlay with the "play/install" and "information" icons would appear on that cover. 

I have attached a video that might illustrate the behaviour better. 

This behaviour only began to arise in versions 1.51 and 1.52. I made no changes to settings since installing the latest version of Helium. 

I tried modifying the settings as you suggested but it didn't resolve the issue. 

As per the OP, the issue is resolved by regressing back to version 1.50.

Thank you,

**Comment by sengtsan** [comment] 2023-12-07 23:06
For clarity, I uninstalled 1.52 and reinstalled 1.50 and attach this short video of how the earlier version behaves. 

https://github.com/darklinkpower/Helium/assets/63714826/6cf2a9f1-e2f8-442b-9ebb-875a0171221d

**Comment by darklinkpower** [comment] 2023-12-09 15:47
Thanks for the video. Fixed in https://github.com/darklinkpower/Helium/commit/955322366957505f693f9570c6a92779a41be88e and is available in new update.

**Closed by darklinkpower** 2023-12-09 15:47 UTC
Labels: bug
